apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pawbridge-connect-postgresql-secret-reader
  namespace: pawbridge-dev
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - dev-animal-postgresql-cdc-auth
  - dev-user-postgresql-cdc-auth
  - dev-community-postgresql-cdc-auth
  - dev-store-postgresql-cdc-auth
  - dev-payment-postgresql-cdc-auth
  verbs:
  - get
