apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cdc-animal-heartbeat-topic.yaml
- cdc-animal.yaml
- cdc-community-heartbeat-topic.yaml
- cdc-community.yaml
- cdc-payment-heartbeat-topic.yaml
- cdc-payment.yaml
- cdc-secret-provider-binding.yaml
- cdc-secret-provider-rbac.yaml
- cdc-store-heartbeat-topic.yaml
- cdc-store.yaml
- cdc-user-heartbeat-topic.yaml
- cdc-user.yaml
- connect.yaml
- kafka-kafka-cluster.yaml
- kafka-kafka-node-pool.yaml
- kafka-topics-business.yaml
- kafka-topics-connect-internal.yaml
- namespace.yaml
- network.yaml
- postgresql-config.yaml
- postgresql-service-headless.yaml
- postgresql-service.yaml
- postgresql-statefulset.yaml
- quota.yaml
- redis-service-headless.yaml
- redis-service.yaml
- redis-statefulset.yaml
