apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-budget
  namespace: pawbridge-dev
spec:
  hard:
    requests.cpu: '6'
    limits.cpu: '14'
    requests.memory: 8Gi
    limits.memory: 12Gi
    requests.storage: 24Gi
    pods: '30'
    services.nodeports: '0'
    services.loadbalancers: '0'
