apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: animal-search-runtime-vso
  namespace: argocd
spec:
  project: pawbridge-animal-search-vso
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: gitops/security/animal-search-vso/runtime
  destination:
    server: https://kubernetes.default.svc
    namespace: pawbridge
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
