apiVersion: v1
kind: ServiceAccount
metadata:
  name: animal-search-pawbridge-vault-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: animal-search-pawbridge-vault-connection
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: vault-internal-ca
  skipTLSVerify: false
  tlsServerName: vault.vault.svc.cluster.local
  timeout: 10s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: animal-search-pawbridge-vault-auth
  namespace: pawbridge
spec:
  vaultConnectionRef: animal-search-pawbridge-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: animal-search-pawbridge-read
    serviceAccount: animal-search-pawbridge-vault-auth
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: animal-search-writer-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: animal-search-pawbridge-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/animal/elasticsearch/writer
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: animal-search-writer-auth
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      includes:
        - ^username$
        - ^password$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: animal-search-http-ca
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: animal-search-pawbridge-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/animal/elasticsearch/trust
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: animal-search-http-ca
    transformation:
      excludeRaw: true
      includes:
        - ^ca[.]crt$
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-search-pawbridge-vault-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: python-search-pawbridge-vault-connection
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: vault-internal-ca
  skipTLSVerify: false
  tlsServerName: vault.vault.svc.cluster.local
  timeout: 10s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: python-search-pawbridge-vault-auth
  namespace: pawbridge
spec:
  vaultConnectionRef: python-search-pawbridge-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: python-search-pawbridge-read
    serviceAccount: python-search-pawbridge-vault-auth
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: python-search-writer-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: python-search-pawbridge-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/python/elasticsearch/writer
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: python-search-writer-auth
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      includes:
        - ^username$
        - ^password$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: python-search-http-ca
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: python-search-pawbridge-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/python/elasticsearch/trust
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: python-search-http-ca
    transformation:
      excludeRaw: true
      includes:
        - ^ca[.]crt$
