apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pawbridge-store-pilot
  namespace: argocd
spec:
  description: Store Service manual-sync pilot
  sourceRepos:
    - https://github.com/pawbridge/pawbridge-infra-k8s.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: pawbridge
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: monitoring.coreos.com
      kind: ServiceMonitor
