apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: store-r2-shadow
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: store-r2-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/store/r2
  refreshAfter: 1m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: store-service
  destination:
    create: true
    overwrite: false
    name: store-service-r2-secrets-vso
    transformation:
      excludeRaw: true
      includes:
        - ^R2_ACCESS_KEY_ID$
        - ^R2_SECRET_ACCESS_KEY$
