apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: pawbridge-local-path-provisioner-pilot
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: gitops/cluster-addons/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
