apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pawbridge-connect-secret-reader
  namespace: kafka
  labels:
    app.kubernetes.io/name: pawbridge-kafka-connect
    app.kubernetes.io/part-of: pawbridge
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - store-search-writer-auth
      - store-mysql-cdc-auth
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pawbridge-connect-secret-reader
  namespace: kafka
  labels:
    app.kubernetes.io/name: pawbridge-kafka-connect
    app.kubernetes.io/part-of: pawbridge
subjects:
  - kind: ServiceAccount
    name: pawbridge-connect-connect
    namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pawbridge-connect-secret-reader
