apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pawbridge-es-source-snapshots
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
