- op: add
  path: /spec/auth/fileRealm/-
  value:
    secretName: pawbridge-es-migration-auth
- op: add
  path: /spec/auth/roles/-
  value:
    secretName: pawbridge-es-migration-roles
- op: add
  path: /spec/nodeSets/0/config/path.repo
  value: [/mnt/pawbridge-snapshots]
- op: add
  path: /spec/nodeSets/0/podTemplate/spec/volumes
  value:
    - name: migration-snapshots
      persistentVolumeClaim:
        claimName: pawbridge-es-source-snapshots
- op: add
  path: /spec/nodeSets/0/podTemplate/spec/containers/0/volumeMounts
  value:
    - name: migration-snapshots
      mountPath: /mnt/pawbridge-snapshots
