apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: pawbridge-pg-community-heartbeat
  namespace: kafka
  labels:
    strimzi.io/cluster: pawbridge
    app.kubernetes.io/part-of: pawbridge
spec:
  topicName: __debezium-heartbeat.pawbridge-pg-community
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact
    segment.bytes: 1048576
    max.compaction.lag.ms: 60000
