apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- animal.yaml
- user.yaml
- community.yaml
- store.yaml
- payment.yaml
- secret-provider-rbac.yaml
- secret-provider-binding.yaml
- animal-heartbeat-topic.yaml
- user-heartbeat-topic.yaml
- community-heartbeat-topic.yaml
- store-heartbeat-topic.yaml
- payment-heartbeat-topic.yaml
