apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pawbridge-connect-postgresql-secret-reader
  namespace: kafka
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - animal-postgresql-cdc-auth
  - user-postgresql-cdc-auth
  - community-postgresql-cdc-auth
  - store-postgresql-cdc-auth
  - payment-postgresql-cdc-auth
  verbs:
  - get
