apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-dev
  namespace: argocd
spec:
  project: pawbridge-cloudflared-pilot
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: infra/network
  destination:
    server: https://kubernetes.default.svc
    namespace: pawbridge
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
