apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-postgresql-vault-auth
  namespace: pawbridge
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: store-postgresql-vault-auth
  namespace: pawbridge
spec:
  vaultConnectionRef: postgresql-runtime-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: store-postgresql-read
    serviceAccount: store-postgresql-vault-auth
    audiences:
    - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: store-postgresql-auth
  namespace: pawbridge
spec:
  vaultAuthRef: store-postgresql-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/store/postgresql
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    name: store-postgresql-auth
    create: true
    overwrite: false
    transformation:
      excludeRaw: true
      includes:
      - ^postgres-password$
