apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../original
  - snapshot-pvc.yaml
secretGenerator:
  - name: pawbridge-es-restore-roles
    namespace: databases
    files:
      - roles.yml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Secret
      name: store-search-file-realm-roles
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: store-search-file-realm-roles
        namespace: databases
  - target:
      kind: Elasticsearch
      name: store-search
    path: restore-patch.yaml
