apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - application.yaml
  - animal-application.yaml
  - community-application.yaml
  - payment-application.yaml
