apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: user-google-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: user-runtime-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/user/google
  refreshAfter: 1m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: user-service
  destination:
    create: true
    overwrite: false
    name: user-google-auth
    transformation:
      excludeRaw: true
      includes:
        - ^GOOGLE_EMAIL$
        - ^GOOGLE_EMAIL_SECRET_KEY$
        - ^GOOGLE_CLIENT_ID$
        - ^GOOGLE_SECRET_KEY$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: user-jwt-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: user-runtime-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/target-edge/api-gateway-jwt
  refreshAfter: 1m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: user-service
  destination:
    create: true
    overwrite: false
    name: user-jwt-auth
    transformation:
      excludeRaw: true
      includes:
        - ^JWT_SECRET$
