apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pawbridge-elasticsearch
  namespace: argocd
spec:
  project: pawbridge-elasticsearch-pilot
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: gitops/stateful/elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
