apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-test
  namespace: argocd
spec:
  project: pawbridge-dev
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: charts/api-gateway
    helm:
      releaseName: api-gateway
      valueFiles:
      - ../../environments/dev/isolated-values/api-gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pawbridge-dev
  syncPolicy:
    syncOptions:
    - Prune=false
    - FailOnSharedResource=true
