apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pawbridge-dev
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/pawbridge/pawbridge-infra-k8s.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: pawbridge-dev
  namespaceResourceWhitelist:
  - group: apps
    kind: Deployment
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: batch
    kind: Job
  - group: batch
    kind: CronJob
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  - group: secrets.hashicorp.com
    kind: VaultStaticSecret
