{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-boundary
  labels:
    app: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.cloudflaredPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.namespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podSelector | nindent 14 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- range .Values.networkPolicy.sameNamespaceServices }}
    - to:
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .port }}
    {{- end }}
    {{- range .Values.networkPolicy.crossNamespaceServices }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .podSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .port }}
    {{- end }}
{{- end }}
