apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: target-edge-vso
  namespace: argocd
spec:
  project: pawbridge-target-edge-vso
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: gitops/security/target-edge-vso
  destination:
    server: https://kubernetes.default.svc
    namespace: pawbridge
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
