apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: community-youtube
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: community-youtube-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/community/youtube
  refreshAfter: 1m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: community-service
  destination:
    create: true
    overwrite: false
    name: community-youtube-auth
    transformation:
      excludeRaw: true
      includes:
        - '^YOUTUBE_DATA_API_KEY$'
