apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- animal-service.yaml
- api-gateway.yaml
- community-service.yaml
- lost-search-gpu-proxy.yaml
- payment-service.yaml
- photo-service.yaml
- project.yaml
- python-ai-service.yaml
- store-service.yaml
- user-service.yaml
