apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller-broker
  namespace: kafka
  labels:
    strimzi.io/cluster: pawbridge
    app.kubernetes.io/name: pawbridge-kafka
    app.kubernetes.io/part-of: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  roles:
    - controller
    - broker
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 8Gi
        class: local-path
        deleteClaim: false
        kraftMetadata: shared
