apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
configMapGenerator:
  - name: store-search-index-v001-mapping
    namespace: databases
    files:
      - store-index-mapping.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: store-search-index-v001
    app.kubernetes.io/instance: pawbridge
    app.kubernetes.io/component: search-bootstrap
    app.kubernetes.io/part-of: pawbridge
