apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-search-databases-vault-auth
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: store-search-databases-vault-connection
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: vault-internal-ca
  skipTLSVerify: false
  tlsServerName: vault.vault.svc.cluster.local
  timeout: 10s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: store-search-databases-vault-auth
  namespace: databases
spec:
  vaultConnectionRef: store-search-databases-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: store-search-databases-read
    serviceAccount: store-search-databases-vault-auth
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: store-search-reader-auth
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: store-search-databases-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/store/elasticsearch/reader
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: store-search-reader-auth
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      includes:
        - ^username$
        - ^password$
        - ^roles$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: store-search-writer-auth
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: store-search-databases-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/store/elasticsearch/writer
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: store-search-writer-auth
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      includes:
        - ^username$
        - ^password$
        - ^roles$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: store-search-bootstrap-auth
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: store-search-databases-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/store/elasticsearch/bootstrap
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: store-search-bootstrap-auth
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      includes:
        - ^username$
        - ^password$
        - ^roles$
