apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-client-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: redis-client-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/redis/auth
  refreshAfter: 1m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: animal-service
    - kind: Deployment
      name: store-service
    - kind: Deployment
      name: user-service
  destination:
    create: true
    overwrite: false
    name: redis-auth
    transformation:
      excludeRaw: true
      includes:
        - ^redis-password$
