apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-auth
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: redis-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/redis/auth
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: redis-auth
    transformation:
      excludeRaw: true
      includes:
        - ^redis-password$
