apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pawbridge-animal-service-pilot
  namespace: argocd
spec:
  description: Animal Service manual-sync pilot
  sourceRepos:
    - https://github.com/pawbridge/pawbridge-infra-k8s.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: pawbridge
  namespaceResourceWhitelist:
    - group: batch
      kind: Job
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: batch
      kind: CronJob
  orphanedResources:
    warn: true
