apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: community-mysql-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: community-mysql-vault-auth
  mount: secret
  type: kv-v2
  path: pawbridge/dev/community/mysql
  refreshAfter: 1m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: community-service
  destination:
    create: true
    overwrite: false
    name: community-mysql-auth
    transformation:
      excludeRaw: true
      includes:
        - ^mysql-password$
