apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: databases
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: pawbridge
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pawbridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: pawbridge
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
