pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 256; }
stream {
 server { listen 18025; set $upstream mail:8025; proxy_connect_timeout 3s; proxy_timeout 30s; proxy_pass $upstream; }
 server { listen 11025; set $upstream mail:1025; proxy_connect_timeout 3s; proxy_timeout 30s; proxy_pass $upstream; }
 resolver 127.0.0.11 valid=10s ipv6=off;
 server { listen 15433; set $upstream postgresql:5432; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 16379; set $upstream redis:6379; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 19092; set $upstream kafka:19092; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 18383; set $upstream connect:8083; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28080; set $upstream api-gateway:8080; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28081; set $upstream user-service:8080; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28082; set $upstream animal-service:8081; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28083; set $upstream community-service:8082; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28084; set $upstream store-service:8083; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28085; set $upstream payment-service:8084; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28086; set $upstream photo-service:8000; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
 server { listen 28087; set $upstream python-ai-service:8000; proxy_connect_timeout 3s; proxy_timeout 300s; proxy_pass $upstream; }
}
