bootstrap.servers=kafka:9092
group.id=pawbridge-local-dev-connect
config.storage.topic=dev-connect-configs
offset.storage.topic=dev-connect-offsets
status.storage.topic=dev-connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
listeners=http://0.0.0.0:8083
rest.advertised.host.name=connect
plugin.path=/opt/kafka/plugins
config.providers=file
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
