apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-vault-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-tunnel-vault-auth
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
