apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: target-edge-vault-connection
  namespace: pawbridge
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: vault-internal-ca
  skipTLSVerify: false
  tlsServerName: vault.vault.svc.cluster.local
  timeout: 10s
