apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-slack-vso
  namespace: argocd
spec:
  project: pawbridge-observability-secrets
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: gitops/security/observability-vso/slack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
