apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- network-policy.yaml
- service-local.yaml
- service.yaml
- service-headless.yaml
- statefulset.yaml
configMapGenerator:
- name: pawbridge-postgresql-config
  namespace: databases
  files:
  - postgresql.conf
generatorOptions:
  disableNameSuffixHash: false
