apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pawbridge-runtime-baseline
  namespace: argocd
spec:
  project: pawbridge-runtime-baseline
  source:
    repoURL: https://github.com/pawbridge/pawbridge-infra-k8s.git
    targetRevision: dev
    path: gitops/platform/pawbridge-runtime
  destination:
    server: https://kubernetes.default.svc
    namespace: pawbridge
  syncPolicy:
    syncOptions:
      - Prune=false
      - FailOnSharedResource=true
